# Generated by Django 3.1.3 on 2022-04-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
                ('img_type', models.IntegerField(default=1)),
                ('img_path', models.CharField(default='./static/media/upload.jpg', max_length=20)),
                ('create_time', models.DateTimeField()),
            ],
        ),
    ]
