# Generated by Django 3.1.3 on 2022-04-26 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inpainting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ticket',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
