# Generated by Django 3.1.3 on 2022-04-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inpainting', '0002_auto_20220426_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='img_path',
            new_name='upload_path',
        ),
        migrations.AddField(
            model_name='user',
            name='result_path',
            field=models.CharField(default='./static/media/result.jpg', max_length=20),
        ),
    ]
