# Generated by Django 3.1.3 on 2022-04-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inpainting', '0003_auto_20220426_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mask_path',
            field=models.CharField(default='./static/media/mask.png', max_length=20),
        ),
    ]
