# Generated by Django 3.1.3 on 2022-04-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inpainting', '0004_user_mask_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='mask_path',
            field=models.CharField(default='./static/media/mask.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='pwd',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='result_path',
            field=models.CharField(default='./static/media/result.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='upload_path',
            field=models.CharField(default='./static/media/upload.jpg', max_length=255),
        ),
    ]
